import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class TimetablePdf {
  static pw.Document generate(List<Map<String, dynamic>> data) {
    final pdf = pw.Document();

    List<String> days = [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
    ];

    List<String> hours = ["9-11", "11-1", "1-3", "3-5"];

    String getCell(String day, String hour) {
      final item = data
          .where((e) => e["day"] == day && e["hour"] == hour)
          .toList();

      if (item.isEmpty) return "-";

      final e = item.first;

      return "${e["subject"]}\nDr ${e["doctorId"]}\n${e["room"]}";
    }

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4.landscape,
        margin: const pw.EdgeInsets.all(20),

        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              /// 🟦 HEADER
              buildHeader(),

              pw.SizedBox(height: 20),

              /// 🧾 TABLE TITLE
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Text(
                  "Weekly Lecture Timetable",
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue800,
                  ),
                ),
              ),

              pw.SizedBox(height: 15),

              /// 📊 TABLE
              pw.Table.fromTextArray(
                border: pw.TableBorder.all(
                  color: PdfColors.grey400,
                  width: 0.5,
                ),

                headerDecoration: const pw.BoxDecoration(
                  color: PdfColors.blue100,
                ),

                cellAlignment: pw.Alignment.center,

                headers: ["Day", ...hours],

                data: days.map((day) {
                  return [day, ...hours.map((h) => getCell(day, h)).toList()];
                }).toList(),

                headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 11,
                  color: PdfColors.blue900,
                ),

                cellStyle: const pw.TextStyle(fontSize: 9),
              ),

              pw.Spacer(),

              /// 🟢 FOOTER
              buildFooter(),
            ],
          );
        },
      ),
    );

    return pdf;
  }

  /// ================= HEADER =================
  static pw.Widget buildHeader() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: const pw.BoxDecoration(color: PdfColors.blue900),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          /// 🏫 LOGO PLACEHOLDER
          pw.Container(
            width: 50,
            height: 50,
            decoration: const pw.BoxDecoration(
              color: PdfColors.white,
              shape: pw.BoxShape.circle,
            ),
            child: pw.Center(
              child: pw.Text(
                "U",
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
          ),

          /// TITLE
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Text(
                "University Scheduling System",
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                "Generated Timetable Report",
                style: const pw.TextStyle(color: PdfColors.white, fontSize: 10),
              ),
            ],
          ),

          /// DATE
          pw.Text(
            DateTime.now().toString().split(" ").first,
            style: const pw.TextStyle(color: PdfColors.white, fontSize: 10),
          ),
        ],
      ),
    );
  }

  /// ================= FOOTER =================
  static pw.Widget buildFooter() {
    return pw.Container(
      alignment: pw.Alignment.center,
      padding: const pw.EdgeInsets.all(10),
      child: pw.Text(
        "Generated by Admin System • Confidential Document",
        style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
      ),
    );
  }
}
